#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# your commands here

#load samtools utilities
module load samtools bowtie2 boost tophat

#defining input files
file_1="/projectnb/bf528/users/group7/project2/project-2-group-7/project2/scripts/P0_1_1.fastq"
file_2="/projectnb/bf528/users/group7/project2/project-2-group-7/project2/scripts/P0_1_2.fastq"

# run tophat
tophat -r 200 -G /project/bf528/project_2/reference/annot/mm9.gtf --segment-length=20 --segment-mismatches=1 --no-novel-juncs -o P0_1_tophat -p 16 /project/bf528/project_2/reference/mm9 $file_1 $file_2

echo "Job finished: $(date +%F)"
