#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# your commands here

# load modules
module load python3 samtools rseqc

# run geneBody_coverage.py
geneBody_coverage.py -i accepted_hits.bam -r /project/bf528/project_2/reference/annot/mm9.bed -o accepted_hits_gBout

echo "Job finished: $(date +%F)"
